general:
    data_type: raw
    run: DLSraw

    plot_sample: True
    plot_reset: True
    plot_combined: True

all:
    output: &output /Users/ben/PostDoc/P2M_HDF5/Data_0918/Coarse_scan

raw:
    input: /Users/ben/PostDoc/P2M_HDF5/Data_0918/DLSraw/correction/col0-1439_correction.h5
    metadata_fname: null 

    output: *output

    measurement: adccal

    adc: null
    frame: 2
    col: 100
    row: 100

    method: [viewer]

    viewer:
      err_below: -0.1
    #method: [image, plot_coarse-fine_vs_image]

gathered:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 100
    row: null

    method: [plot, hist, hist_2d]
    #method: [plot_sample_vs_reset]

processed:
    input: *output
    output: *output

    measurement: adccal

    adc: 0
    frame: null
    col: 10
    row: null

    method: [plot]
